#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/5fe8ba42-040f-466f-a8c3-e62dd264cc9f/ # 
title: Orders MB Shop
version: v1
mediaType: application/json
uses: 
  types: libraries/types.raml
  traits: libraries/traits.raml
/orders:
  /{orderId}:
    uriParameters:
      orderId:
        type: number
    get:
      is: [traits.client-id-required]
      responses:
        200:
          body:
            application/json:
              type: types.Order
             
        404:
          body:
            application/json:
              example:
                {"error": "not found"}
          